In [10]:
#创建训练集，6条留言以及标定的是否具有侮辱性，1为侮辱性留言，0为正常留言。
def loadDataSet():
    postingList=[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
                 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
                 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
                 ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
                 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
                 ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]
    classVec = [0,1,0,1,0,1]    #1 is abusive, 0 not
    return postingList,classVec
#创建给定训练集的无重复词汇表
def createVocablist(dataSet):
    vocabList = set([])
    for document in dataSet:
        vocabList = vocabList | set(document)
    #将set转为list形式，使无序变为有序
    return list(vocabList)
#使无重复词汇文档变成向量文档，便于训练
def setOfWords2Vec(dataSet,inputSet):
    returnVec = [0]*len(dataSet)
    for word in inputSet:
        if word in dataSet:
            returnVec[dataSet.index(word)] = 1
        else:print("no including")
    return returnVec
postingList,classVec = loadDataSet()
createVocablist = createVocablist(postingList)
setOfWords2Vec(createVocablist,postingList[1])

[1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0]

In [14]:
import numpy as np
a = np.zeros(4)
a

array([ 0.,  0.,  0.,  0.])

In [18]:
import numpy as np
data2 = [[1,2,3,4],[5,6,7,8]]
arr2 = np.array(data2)
data2*10

[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [1, 2, 3, 4],
 [5, 6, 7, 8],
 [1, 2, 3, 4],
 [5, 6, 7, 8],
 [1, 2, 3, 4],
 [5, 6, 7, 8],
 [1, 2, 3, 4],
 [5, 6, 7, 8],
 [1, 2, 3, 4],
 [5, 6, 7, 8],
 [1, 2, 3, 4],
 [5, 6, 7, 8],
 [1, 2, 3, 4],
 [5, 6, 7, 8],
 [1, 2, 3, 4],
 [5, 6, 7, 8],
 [1, 2, 3, 4],
 [5, 6, 7, 8]]

In [23]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [24]:
arr2.dtype

dtype('int32')

In [28]:
new_arr2 = np.array(arr2,dtype = np.float64)
new_arr2.dtype

dtype('float64')

In [36]:
arr1 = np.arange(10)
arr1.astype(new_arr2.dtype)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [37]:
arr = np.arange(10)
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [38]:
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [39]:
arr_slice[:] = 123
arr

array([  0,   1,   2,   3,   4, 123, 123, 123,   8,   9])

In [45]:
arr2d = np.random.randn(4,4)
arr2d[1][3]

2.4498639758900573

In [46]:
arr2d[1] = 32
arr2d

array([[ -1.48388244e-01,   8.33424897e-02,  -1.78075028e+00,
          6.83290548e-01],
       [  3.20000000e+01,   3.20000000e+01,   3.20000000e+01,
          3.20000000e+01],
       [ -5.42347847e-01,  -5.09623418e-01,   7.27576860e-01,
         -1.21985042e+00],
       [ -1.07071240e+00,   6.63668952e-01,   7.82600030e-01,
          1.79395756e-02]])

In [49]:
arr2d[:2,1:]

array([[  0.08334249,  -1.78075028,   0.68329055],
       [ 32.        ,  32.        ,  32.        ]])

names = np.array("a","b","c","d")
names

In [53]:
names = np.array(["a","b","x","d","a","x"])
names

array(['a', 'b', 'x', 'd', 'a', 'x'],
      dtype='<U1')

In [64]:
data = np.random.randn(6,4)
data[(data>0)] = 0
data

array([[ 0.        , -1.39189428,  0.        ,  0.        ],
       [-0.63311479,  0.        ,  0.        , -1.0813171 ],
       [-0.5640341 , -0.16383005, -0.33740681, -0.01894816],
       [-0.97939571, -1.53428001, -0.59331253, -0.72828528],
       [-0.22084275,  0.        ,  0.        , -0.90477389],
       [-0.27745783,  0.        , -1.78469758, -0.3151622 ]])

In [55]:
data.rowname = names

AttributeError: 'numpy.ndarray' object has no attribute 'rowname'

In [83]:
arr = np.empty((4,4))
for i in range(4):
    arr[i] = i
arr[[-1,2]]

array([[ 3.,  3.,  3.,  3.],
       [ 2.,  2.,  2.,  2.]])

In [88]:
arr = np.arange(32).reshape(8,4)
arr[[2,3,4,5]][:,[3,2,1,0]]

array([[11, 10,  9,  8],
       [15, 14, 13, 12],
       [19, 18, 17, 16],
       [23, 22, 21, 20]])

In [91]:
arr = np.arange(15).reshape(3,5)
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [98]:
arr = np.array([[1,2],[1,3]])
arr.T

array([[1, 1],
       [2, 3]])

In [99]:
np.dot(arr.T,arr)

array([[ 2,  5],
       [ 5, 13]])

In [104]:
x = np.random.randn(8)
y = np.random.randn(8)
np.maximum(x,y)

array([ 1.46754172,  1.70038309,  1.61008677,  0.30439152,  1.32129854,
        1.09074791,  0.77376468,  0.24181381])

In [110]:
np.log10(10)

1.0

In [121]:
pointsx = np.arange(-5,5,1)
pointsy = np.arange(-10,10,2)
pointsx

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [124]:
xs,ys = np.meshgrid(pointsy,pointsy)
xs.T

array([[-10, -10, -10, -10, -10, -10, -10, -10, -10, -10],
       [ -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8],
       [ -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6,  -6],
       [ -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4],
       [ -2,  -2,  -2,  -2,  -2,  -2,  -2,  -2,  -2,  -2],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  2,   2,   2,   2,   2,   2,   2,   2,   2,   2],
       [  4,   4,   4,   4,   4,   4,   4,   4,   4,   4],
       [  6,   6,   6,   6,   6,   6,   6,   6,   6,   6],
       [  8,   8,   8,   8,   8,   8,   8,   8,   8,   8]])

In [127]:
True - False

1

In [132]:
arr = np.arange(20).reshape(4,5)
arr.mean(axis = 0)

array([  7.5,   8.5,   9.5,  10.5,  11.5])

In [133]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [141]:
arr = np.random.randn(4,5)
arr

array([[ 0.01159332,  0.64011187,  0.11054494,  1.11097704, -0.76485225],
       [-1.06839952, -1.05009127, -0.3829292 ,  1.19848637,  0.08359034],
       [-0.10266924, -0.5369559 , -0.77080013, -1.50693846, -0.26632375],
       [ 0.82217325, -0.14404126, -0.55908835,  0.77367902,  0.55308165]])

In [144]:
np.sort(arr,0)

array([[-1.06839952, -1.05009127, -0.77080013, -1.50693846, -0.76485225],
       [-0.10266924, -0.5369559 , -0.55908835,  0.77367902, -0.26632375],
       [ 0.01159332, -0.14404126, -0.3829292 ,  1.11097704,  0.08359034],
       [ 0.82217325,  0.64011187,  0.11054494,  1.19848637,  0.55308165]])

In [148]:
arr = np.arange(1000)
arr.sort()
arr[int(0.05*len(arr))]

50

In [149]:
arr[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
list(arr[:10])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [153]:
np.ones(3)

array([ 1.,  1.,  1.])

In [154]:
a = np.arange(6).reshape(2,3)
b = np.arange(6).reshape(3,2)
a.dot(b)

array([[10, 13],
       [28, 40]])

In [156]:
matrixa = np.matrix(a)
matrixb = np.matrix(b)
matrixa*matrixb

matrix([[10, 13],
        [28, 40]])

In [157]:
A = np.mat("0 1 2;1 0 3;4 -3 8")
A

matrix([[ 0,  1,  2],
        [ 1,  0,  3],
        [ 4, -3,  8]])

In [160]:
np.linalg.inv(A)

matrix([[-4.5,  7. , -1.5],
        [-2. ,  4. , -1. ],
        [ 1.5, -2. ,  0.5]])

In [167]:
list1 = [1,2,3]
list1

[1, 2, 3]

In [165]:
array = np.arange(3)
array

array([0, 1, 2])

In [166]:
array*2

array([0, 2, 4])

In [168]:
list1*2

[1, 2, 3, 1, 2, 3]